<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cziel_utils"
 *
 * Auto generated by Extension Builder 2013-05-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Extbase / Fluid Components',
	'description' => 'A collection of useful extbase / fluid components',
	'category' => 'plugin',
	'author' => 'Cedric Ziel',
	'author_email' => 'cedric@cedric-ziel.com',
	'author_company' => 'Cedric Ziel - Internetdienstleistungen & EDV',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0'
		),
		'conflicts' => array(),
		'suggests' => array(),
	),
);

?>
